city=input("Choose a city: ")
noun=input("Choose a noun: ")
noun2=input("Choose a noun: ")
adjective=input("Choose an adjective: ")
plnoun =input("Choose a plural noun: ")
print ("------------------------------------------")
print ("Me and my friends went to ",city,"by",noun,)
print ("As soon as we arrived there we bought some ",plnoun,"and a ",noun2,"which were",adjective)
print ("------------------------------------------")